server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:product
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#
#kafka:
#  bootstrap-servers: localhost:9092
#  producer:
#    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#  consumer:
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#  topic:
#    input: product_topic
#    output: product_topic
